### ISSUE TITLE
Python2.7 support?

### ISSUE THREAD

**Issue by gregplaysguitar** [glut23/webvtt-py#1]
Hi, any idea what it would take to make this support python2.7? I could potentially do the work but wanted to get your thoughts first.

**Comment by glut23** [comment]
Hi @gregplaysguitar I think mostly how to deal with files but it shouldn't take much effort I guess. It would be great if you make it support 2.7! :)

**Comment by jvetu** [comment]
Hi @gregplaysguitar did you ever give this a shot? If not I might have a go :)

**Comment by gregplaysguitar** [comment]
Sorry, I didn't end up going down this route. From memory I think I used pyvtt instead

**Comment by OmarIthawi** [comment]
Hi @glut23 would you have the time to do a quick review if Python 2.7 is introduced? It would be great to support that for projects which are stuck for now.

**Comment by glut23** [comment]
Hi @OmarIthawi thanks for taking the time to look at supporting Python 2.7. I have limited time unfortunately but I would be glad to review. I see your PR does not include running the test suite with Travis, could you add that in please?

**Comment by OmarIthawi** [comment]
Thanks @glut23 any minimal review would do! So that would be great :)

**Comment by funkyfuture** [comment]
by now there's no doubt that this idea is obsolete, or is there?
