### ISSUE TITLE
MalformedCaptionError 

### ISSUE THREAD

**Issue by methodds** [glut23/webvtt-py#12]
Hi, I'm not sure whether this is related to the other issues so I opened a new one. I have issues with loadin in a [youtube VTT file](https://www.dropbox.com/s/9bptx237mpsg19n/PdUpXrgzSrI.de.vtt?dl=1):
```
MalformedCaptionError                     Traceback (most recent call last)
<ipython-input-10-cf8d0e78a7c6> in <module>()
----> 1 WebVTT().read('PdUpXrgzSrI.de.vtt')

~/anaconda3/lib/python3.6/site-packages/webvtt/main.py in f(self, file)
     50         def f(self, file):
     51             self.file = file
---> 52             self._captions = parser_class().read(file).captions
     53             return self
     54 

~/anaconda3/lib/python3.6/site-packages/webvtt/generic.py in read(self, file)
    117         content = self._read_content(file)
    118         self._validate(content)
--> 119         self._parse(content)
    120 
    121         return self

~/anaconda3/lib/python3.6/site-packages/webvtt/parsers.py in _parse(self, lines)
     68                     continue
     69                 if not c.lines:
---> 70                     raise MalformedCaptionError('Caption missing text in line {}.'.format(index + 1))
     71 
     72                 self.captions.append(c)

MalformedCaptionError: Caption missing text in line 12.
```
WebVTT version is 0.3.3

**Comment by glut23** [comment]
Hi @methodds looking at the error trace you provided we get a hint of the problem. In line 12 we have a caption missing the text. I read the file you attached and I see same thing happens for few captions. I had a look at the problematic ones and saw a space was used to force the caption text to display in the second line. At the moment the parser removes those spaces and that is why it raises an error. I will update the parser to fix it. I was planning to release an update today or tomorrow with new features and it can also contain this fix. I will let you know when this happens. Thanks for reporting the issue.

**Comment by methodds** [comment]
Awesome, thank you :)

**Comment by glut23** [comment]
Hi @methodds I just released version 0.4.0 that should fix this issue. Thanks!

**Comment by methodds** [comment]
that was super fast, thank **you** :)

**Comment by glut23** [comment]
Closing this issue as it was solved.
