### ISSUE TITLE
.save() does not save identifiers

### ISSUE THREAD

**Issue by KingWalrus** [glut23/webvtt-py#14]
Hi, 
I am experimenting with doing automatic translations on some VTT files and I noticed when I save out the file, it does save the identifier lines in the new file. Even if I do not change the file at all they are not present in the saved file. 

I will take a look and see if I can fix it and let you know. 

C

**Comment by glut23** [comment]
Hi @KingWalrus, apologies for the late reply. Just released 0.4.1 that will save cue identifiers. Thanks!

**Comment by glut23** [comment]
Closing this as issue is resolved.

**Comment by KingWalrus** [comment]
Thank you!
