### ISSUE TITLE
according to WebVTT specification hours field is optional when hours is zero

### ISSUE THREAD

**Issue by mzagrabe** [glut23/webvtt-py#2]
Greetings,

I just started looking at your module. Thanks for writing free software!

I attempted to parse a vtt file that ffmpeg generated and an exception was raised.

The ffmpeg generated file doesn't have the hours field of the timestamp if the hours is zero.

For instance:

01:11.913 --> 01:13.346

whereas the SRT file does:

00:01:11,913 --> 00:01:13,346

This seems to be within the WebVTT spec. From:

https://www.w3.org/TR/webvtt1/

we see:

"""
A WebVTT timestamp consists of the following components, in the given order:

Optionally (required if hours is non-zero):
Two or more ASCII digits, representing the hours as a base ten integer.
A U+003A COLON character (:)
"""

Looking at the regex in your code, the hours field (and its separation colon) is required.

Thanks for looking into this.

-m

**Comment by glut23** [comment]
Hi @mzagrabe thanks for looking at the code and report the issue with all those details. I've made the changes so now the hours are optional for WebVTT timestamps.

**Comment by glut23** [comment]
62d09bb61f381e85bf5baca8de2e514f54f09fe4

**Comment by glut23** [comment]
Hi @mzagrabe 0.3.1 release is now available to install via pip. Thanks!
