### ISSUE TITLE
MalformedCaptionError

### ISSUE THREAD

**Issue by VinuAbraham** [glut23/webvtt-py#28]
MalformedCaptionError: Standalone cue identifier in line 7.

this error is showing reading a vtt file.

**Comment by glut23** [comment]
Hi @VinuAbraham can you provide the first 10 lines of the vtt file?

**Comment by piyh** [comment]
I'm getting the same error.  Downloaded with youtube-dl --write-auto-subs. 

`WEBVTT
Kind: captions
Language: en

00:00:00.030 --> 00:00:05.720 align:start position:0%
 
what's<00:00:00.719><c> up</c><00:00:00.930><c> YouTube</c><00:00:03.529><c> Jam</c><00:00:04.529><c> into</c><00:00:04.859><c> some</c><00:00:05.069><c> new</c><00:00:05.250><c> Ozzy</c>

00:00:05.720 --> 00:00:05.730 align:start position:0%
what's up YouTube Jam into some new Ozzy
 `

**Comment by glut23** [comment]
Hey @piyh can you send me the vtt file please? amendez23@gmail.com thanks!

**Comment by piyh** [comment]
Sent

**Comment by VinuAbraham** [comment]
Problem is with subtitles which are auto generated by youtube

**Comment by glut23** [comment]
Hi @VinuAbraham and @piyh I am preparing an update that is fixing the provided captions file. I will keep you updated.

**Comment by piyh** [comment]
Responsive maintainers are a rare breed 🙏

**Comment by glut23** [comment]
Hey @piyh I just released v0.4.4 that should fix your parsing issue. If you could test and confirm please? Thanks!

**Comment by VinuAbraham** [comment]
Thanks man, will test it..

**Comment by piyh** [comment]
Just verified after a `pip3 install --upgrade webvtt-py` that my script is now working

**Comment by glut23** [comment]
Hey @VinuAbraham could you confirm if your issue is resolved so I can proceed to close this? Thanks.

**Comment by piyh** [comment]
I'd close it out, I haven't had reoccurence
