### ISSUE TITLE
BytesIO support

### ISSUE THREAD

**Issue by drsasa** [glut23/webvtt-py#32]
Hello,

Could we get support for BytesIO ?

Example:

<pre><code>
import webvtt
import BytesIO

with open('test.srt', 'rb') as fh:
    buf = BytesIO(fh.read())

webvtt.from_srt(buf)
</code></pre>

This is not use case but example of what i mean.
Also would be nice to have save to BytesIO too.

Thanks and best all.

**Comment by glut23** [comment]
Hi @drsasa apologies for the very late reply. Support for this has been added in version 0.5.1. Thanks.
