### ISSUE TITLE
BOM in Caption - WEBVTT

### ISSUE THREAD

**Issue by MBelkhechine** [glut23/webvtt-py#37]
Hi,

I would like to thank you first for this handy library.

Like the title suggests, is there a way to generate WEBVTT  text/content with BOM?

I followed the documentation but the result was always without any byte order mark.

**Comment by glut23** [comment]
Hi @MBelkhechine I know I am commenting this very late, but the latest 0.5.0 version includes an improved BOM handling that will allow you to have file with BOM or remove it as needed. Details in the docs. Closing this issue now. Thanks!
