### ISSUE TITLE
MalformedCaptionError: Standalone cue identifier in line 975

### ISSUE THREAD

**Issue by AminodinAkbari** [glut23/webvtt-py#47]
hey @glut23 
i used webvtt-py 0.4.6 and i get this error
`webvtt.errors.MalformedCaptionError: Standalone cue identifier in line 975.`

it's that a bug in library right?
what can i do for it ?

**Comment by barbagus** [comment]
It would help to see your input file around line 975 to say anything. Most probably it indicates your input is actually malformed. I ran into similar issues and this library is actually strict with the [specs](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API).

**Comment by AminodinAkbari** [comment]
Hey,

Big apologies for vanishing from this thread! I actually haven't had access to my GitHub account for a few months and totally missed out on responding here. @glut23 (& @barbagus), really sorry I missed your question—it slipped through the cracks during this time. I’ll catch up on it as soon as I’m back in.

Quick update: I managed to sort out the access issue. It was due to a heavy load on our server which didn’t have enough resources to handle it, nothing technically wrong with your library.

Thanks for your patience!

**Comment by glut23** [comment]
Hey @AminodinAkbari just to let you know that I released 0.5.0 recently and I made the library less strict ignoring blocks that do not conform to specs instead of raising exceptions. Give a try if you can and let me know any feedback. Thanks!
