### ISSUE TITLE
Malformed VTT Cue treated as ok data

### ISSUE THREAD

**Issue by zevlg** [glut23/webvtt-py#49]
https://w3c.github.io/webvtt/#webvtt-cue-block explicitly specifies that VTT Cue ends with the [WebVTT line terminator](https://w3c.github.io/webvtt/#webvtt-line-terminator).   However, in the `test_parse_captions_with_bom` test case the last caption (without WebVTT line terminator) is treated as ok data, but is definitely malformed, because there is no WebVTT line terminator at the end.

**Comment by glut23** [comment]
Hi @zevlg recent changes in the library were made to be less strict that is essentially closer to what video players are doing with caption files. I fixed the output of the WebVTT files produced to have a line break after the last caption to match the specs. 0.5.1 includes the fix. Thanks for raising the issue.
