### ISSUE TITLE
SRT parser cannot handle empty captions.

### ISSUE THREAD

**Issue by sampattuzzi** [glut23/webvtt-py#6]
If there is a double empty line, this should indicate that the caption slot is empty. Software such as Camtasia will generate SRTs with such empty slots.

The a more compatible behaviour would be to parse them as captions with empty content.

**Comment by sampattuzzi** [comment]
Had a stab at fixing here: https://github.com/glut23/webvtt-py/pull/9

**Comment by ishunyu** [comment]
Hi, I've also done a PR for same support for SBV files. #26
